language: python
sudo: false
python:
- '2.7'
- '3.6'
install:
    - "pip install -r chalice/requirements.txt"
    - "pip3 install -r chalice/requirements.txt"
script:
 - python foursight/test.py
 - python3 foursight/test.py
