language: python
sudo: false
python:
- '2.7'
- '3.6'
install:
- pip install -r requirements.txt
- pip install coverage
- pip install coveralls
script:
- coverage run --omit *virtualenv* test.py
- coverage report -m
after_success:
- coveralls
- echo $TRAVIS_PULL_REQUEST
- echo $TRAVIS_BRANCH
- echo $TRAVIS_PYTHON_VERSION
- |
  if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_PYTHON_VERSION == '2.7' ]]; then
    if [[ $TRAVIS_BRANCH == 'master' ]]; then
      chalice deploy --stage dev;
      echo 'Tests succeeded! Deploying to dev stage.';
    fi
    if [[ $TRAVIS_BRANCH == 'production' ]]; then
      chalice deploy --stage prod;
      echo 'Tests succeeded! Deploying to prod stage.';
    fi
  else
    echo 'Tests succeeded, but this is not the time for deployment.';
  fi
