language: python
sudo: false
python:
- '2.7'
- '3.6'
install:
- pip install -r requirements.txt
- pip install coverage
- pip install coveralls
script:
- coverage run --omit *virtualenv* test.py
- coverage report -m
- if [ "$TRAVIS_BRANCH" = "production" ]; then
    if ["$TRAVIS_PYTHON_VERSION" = "2.7"]; then
      echo "Test succeeded! Deploying to prod stage.";
      chalice deploy --stage prod;
    fi
  fi
after_success:
- coveralls
