language: python
sudo: false
python:
  - '2.7'
  - '3.6'
env:
  global:
    - AWS_DEFAULT_REGION=us-east-1
install:
  - "pip install -r requirements.txt"
script:
  - python test.py
  - if [ "$TRAVIS_BRANCH" = "production" ]; then echo "Test succeeded! Deploying to prod stage.";
    chalice deploy --stage prod; fi
